baseURL = "https://blog.7diary.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "技术杂谈"
theme = "ananke"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
statusDir = "static"
dataDir = 'data'
buildDrafts = false

[author]
  name = "flynn.yu"

[[menu.main]]           
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Archives"
  weight = 20
  identifier = "archives"
  url = "/post/"

[params]
  moreMeta = true