baseURL = "https://blog.7diary.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "技术杂谈"
theme = "ananke"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
statusDir = "static"
dataDir = 'data'
buildDrafts = false

[taxonomies]
  category = "categories"
  tag = "tags"