contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
baseURL = "https://yoursite.example.com/"
canonifyURLs = true
title = "My Hugo Site"
[taxonomies]
  category = "categories"
  tag = "tags"
[params]
  subtitle = "Hugo is Absurdly Fast!"
  author = "John Doe"
  
theme = "ananke"